### ISSUE TITLE
dry prerelease uses code.ros.org certs who's ssl cert has expired

### ISSUE THREAD

**Issue by tfoote** [ros-infrastructure/dry_prerelease_job_generator#2]
Command failed: Command '['sudo', 'chroot', '/home/rosbuild/chroot/prerelease_groovy_changepoint_precise_amd64', 'svn', 'co', 'https://code.ros.org/svn/ros/stacks/rosorg/trunk/rosbrowse/certs', '/tmp/chroot_certs']' returned non-zero exit status 1
build/chroot/prerelease_groovy_changepoint_precise_amd64', 'apt-get', 'install', 'subversion', '-y', '--force-yes']
Executing ['sudo', 'chroot', '/home/rosbuild/chroot/prerelease_groovy_changepoint_precise_amd64', 'svn', 'co', 'https://code.ros.org/svn/ros/stacks/rosorg/trunk/rosbrowse/certs', '/tmp/chroot_certs']
Command failed, shutting down chroot:

**Comment by dirk-thomas** [comment]
`code.ros.org` is not available anymore anyway.
